// Sumber data dari chatgpt 2024

const dataResapan = [
  {
    provinsi: "Aceh",
    resapan: "2.42",
    biopori: "1.21",
    taman: "27.93",
  },
  {
    provinsi: "Sumatera Utara",
    resapan: "4.01",
    biopori: "1.47",
    taman: "18.67",
  },
  {
    provinsi: "Sumatera Barat",
    resapan: "1.95",
    biopori: "1.33",
    taman: "30.09",
  },
  {
    provinsi: "Riau",
    resapan: "0.34",
    biopori: "0.49",
    taman: "39.56",
  },
  {
    provinsi: "Jambi",
    resapan: "7.99",
    biopori: "0.8",
    taman: "30.39",
  },
  {
    provinsi: "Sumatera Selatan",
    resapan: "4.13",
    biopori: "1.13",
    taman: "32.58",
  },
  {
    provinsi: "Bengkulu",
    resapan: "1.34",
    biopori: "0",
    taman: "30.39",
  },
  {
    provinsi: "Lampung",
    resapan: "2.88",
    biopori: "0.83",
    taman: "38.79",
  },
  {
    provinsi: "Kepulauan Bangka Belitung",
    resapan: "3.05",
    biopori: "1.89",
    taman: "34.13",
  },
  {
    provinsi: "Kepulauan Riau",
    resapan: "1.56",
    biopori: "0.43",
    taman: "21.71",
  },
  {
    provinsi: "DKI Jakarta",
    resapan: "7.85",
    biopori: "4.58",
    taman: "7.99",
  },
  {
    provinsi: "Jawa Barat",
    resapan: "5.48",
    biopori: "3.23",
    taman: "18.05",
  },
  {
    provinsi: "Jawa Tengah",
    resapan: "3.98",
    biopori: "2.12",
    taman: "26.81",
  },
  {
    provinsi: "DI Yogyakarta",
    resapan: "21.38",
    biopori: "2.53",
    taman: "20.4",
  },
  {
    provinsi: "Jawa Timur",
    resapan: "8.1",
    biopori: "2.61",
    taman: "19.43",
  },
  {
    provinsi: "Banten",
    resapan: "3.61",
    biopori: "1.1",
    taman: "18.93",
  },
  {
    provinsi: "Bali",
    resapan: "4.22",
    biopori: "1.64",
    taman: "33.59",
  },
  {
    provinsi: "Nusa Tenggara Barat",
    resapan: "6.23",
    biopori: "2.94",
    taman: "13.34",
  },
  {
    provinsi: "Nusa Tenggara Timur",
    resapan: "1.92",
    biopori: "0.54",
    taman: "23.42",
  },
  {
    provinsi: "Kalimantan Barat",
    resapan: "4.47",
    biopori: "2.15",
    taman: "52.24",
  },
  {
    provinsi: "Kalimantan Tengah",
    resapan: "0.47",
    biopori: "0.08",
    taman: "33.93",
  },
  {
    provinsi: "Kalimantan Selatan",
    resapan: "4.36",
    biopori: "1.27",
    taman: "21.91",
  },
  {
    provinsi: "Kalimantan Timur",
    resapan: "0.58",
    biopori: "0.38",
    taman: "27.49",
  },
  {
    provinsi: "Kalimantan Utara",
    resapan: "0.18",
    biopori: "0",
    taman: "27.04",
  },
  {
    provinsi: "Sulawesi Utara",
    resapan: "1.72",
    biopori: "1.65",
    taman: "30.73",
  },
  {
    provinsi: "Sulawesi Tengah",
    resapan: "0.66",
    biopori: "0.04",
    taman: "35.08",
  },
  {
    provinsi: "Sulawesi Selatan",
    resapan: "1.78",
    biopori: "1.66",
    taman: "26.66",
  },
  {
    provinsi: "Sulawesi Tenggara",
    resapan: "3.45",
    biopori: "0",
    taman: "37.77",
  },
  {
    provinsi: "Gorontalo",
    resapan: "1.12",
    biopori: "0.09",
    taman: "43.31",
  },
  {
    provinsi: "Sulawesi Barat",
    resapan: "2.34",
    biopori: "0.78",
    taman: "28.39",
  },
  {
    provinsi: "Maluku",
    resapan: "3.67",
    biopori: "4.6",
    taman: "25.11",
  },
  {
    provinsi: "Maluku Utara",
    resapan: "0.07",
    biopori: "0",
    taman: "24.04",
  },
  {
    provinsi: "Papua Barat",
    resapan: "0.24",
    biopori: "0",
    taman: "36",
  },
  {
    provinsi: "Papua",
    resapan: "2.97",
    biopori: "2.13",
    taman: "37.5",
  },
];
